apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grav-sheanxious-data-nas
  namespace: sheanxious
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nas
  accessModes:
    - ReadWriteMany
