apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: go-discord-amputator
  namespace: flux-system
spec:
  secretRef:
    name: universal-image-pull-secret
  image: docker.io/tyzbit/go-discord-amputator
  interval: 2m0s
