apiVersion: v1
kind: Service
metadata:
  name: go-discord-amputator-db
  namespace: personal
spec:
  type: ClusterIP
  selector:
    app: go-discord-amputator-db
  ports:
    - name: tcp-mariadb
      protocol: TCP
      port: 3306
      targetPort: 3306
