apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hotboxfort-neko
  namespace: flux-system
spec:
  targetNamespace: hotboxfort
  chart:
    spec:
      chart: neko
      version: "0.6.3"
      sourceRef:
        kind: HelmRepository
        name: tyzbit
        namespace: flux-system
  interval: 2m0s
  valuesFrom:
    - kind: Secret
      name: hotboxfort-neko
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: mux.${hotboxfort_domain}
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/target: ${cloudflared_tunnel_uuid}.cfargotunnel.com
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
        nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
        acme.cert-manager.io/http01-edit-in-place: "false"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/target: ${cloudflared_tunnel_uuid}.cfargotunnel.com
      hosts:
        - host: movienight.${hotboxfort_domain}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: movienight.${hotboxfort_domain}-tls
          hosts:
            - movienight.${hotboxfort_domain}
    resources:
      requests:
        cpu: 1000m
