apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tyz-gotosocial-longhorn-webapp
  namespace: personal
spec:
  resources:
    requests:
      storage: 40Gi
  volumeMode: Filesystem
  storageClassName: longhorn-webapp
  accessModes:
    - ReadWriteOnce
