apiVersion: v1
kind: ConfigMap
metadata:
  name: writefreely-${discord_cool_name}-config
  namespace: personal
data:
  config.ini: |
    [server]
    port = 8080
    bind = 0.0.0.0
    templates_parent_dir = /go/
    static_parent_dir = /go/
    pages_parent_dir = /go/
    keys_parent_dir = /go/

    [database]
    type = mysql
    username = ${discord_cool_db_username}
    password = ${discord_cool_db_password}
    database = ${discord_cool_db_database}
    host = writefreely-${discord_cool_name}-db
    port = 3306

    [app]
    site_name = ${discord_cool_name}
    site_description = We are cool
    host = https://${discord_cool_domain}
    single_user = true
    min_username_len = 6
    federation = true
    notes_only = false
    public_stats = false
    monetization = false
    wf_modesty = false
