apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grav-${anime_blog_3_name}
  namespace: flux-system
spec:
  targetNamespace: personal
  chart:
    spec:
      chart: grav
      version: "0.3.2"
      sourceRef:
        kind: HelmRepository
        name: tyzbit
        namespace: flux-system
  interval: 2m0s
  values:
    fullnameOverride: grav-${anime_blog_3_name}
    grav:
      image:
        tag: admin
    filebrowser:
      enabled: true
      probes:
        enabled: false
    persistence:
      enabled: true
      existingClaimName: grav-${anime_blog_3_name}-data-nas
    imagePullSecrets:
      - name: docker-hub
    ingress:
      enabled: true
      className: nginx
      annotations:
        acme.cert-manager.io/http01-edit-in-place: "false"
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/target: ${anime_blog_3_domain_ddns}
        nginx.ingress.kubernetes.io/proxy-body-size: 256m
      hosts:
        - host: ${anime_blog_3_domain}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
       - secretName: ${anime_blog_3_domain}-tls
         hosts:
           - ${anime_blog_3_domain}