apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: imagepullsecret-patcher
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m

  wait: false
  prune: false

  path: "./clusters/corpus/core-system/administration/imagepullsecret-patcher"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn: [{ name: kubernetes-secrets }]
  postBuild:
    substituteFrom:
      - kind: Secret
        name: sensitive-values
