apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-vivid-nas
  namespace: personal
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nas
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-vivid-mariadb-longhorn-database
  namespace: personal
spec:
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  storageClassName: longhorn-database
  accessModes:
    - ReadWriteOnce