apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: flux-system
spec:
  releaseName: flaresolverr
  targetNamespace: media
  interval: 2m0s
  chart:
    spec:
      chart: app-template
      version: "1.3.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/flaresolverr/flaresolverr
      tag: v3.0.4

    imagePullSecrets:
      - name: docker-hub

    controller:
      replicas: 1 # active nas

    env:
      TZ: America/New_York

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            port: 8191
            targetPort: 8191

    # ingress:
    #   main:
    #     enabled: true
    #     annotations:
    #       kubernetes.io/ingress.class: nginx
    #       cert-manager.io/cluster-issuer: letsencrypt
    #       acme.cert-manager.io/http01-edit-in-place: "false"
    #       nginx.ingress.kubernetes.io/auth-type: basic
    #       nginx.ingress.kubernetes.io/auth-secret: flaresolverr-credentials
    #       nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    #       external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    #       external-dns.alpha.kubernetes.io/target: ${personal_domain_ddns}
    #     hosts:
    #     - host: "flaresolverr.${personal_domain}"
    #       paths:
    #       - path: "/"
    #     tls:
    #     - hosts:
    #       - "flaresolverr.${personal_domain}"
    #       secretName: flaresolverr.${personal_domain}-tls
