apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-image-keeper
  namespace: flux-system
spec:
  releaseName: kube-image-keeper
  targetNamespace: kuik-system
  interval: 15m
  chart:
    spec:
      chart: kube-image-keeper
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: enix
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
  values:
    controllers:
      image:
        repository: quay.io/enix/kube-image-keeper
      webhook:
        #   objectSelector:
        #     matchExpressions:
        #       - key: kube-image-keeper.enix.io/image-cache
        #         operator: In
        #         values: ["enabled"]
        ignoredNamespaces:
          - kube-system
          - calico-apiserver
          - calico-system
          - longhorn-system
          - tigera-operator
    proxy:
      image:
        repository: quay.io/enix/kube-image-keeper
    registry:
      image:
        repository: public.ecr.aws/docker/library/registry
      persistence:
        enabled: true
        storageClass: longhorn-containerimagecache
        size: 40Gi
