apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sheanxious-neko-firefox-profile-nas
  namespace: media
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nas
  accessModes:
    - ReadWriteOnce
