---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meshcentral-data
  namespace: personal
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-webapp
  resources:
    requests:
      storage: 5Gi
