apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  targetNamespace: media
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 2m0s
  values:
    fullnameOverride: qbittorrent

    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.3.1

    controller:
      replicas: 1 # active nas

    podSecurityContext:
      fsGroup: 568

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            port: 8080
            targetPort: 8080
          torrent-tcp:
            port: 32123
            targetPort: 32123
          torrent-udp:
            port: 32123
            targetPort: 32123
            protocol: UDP
          tracker:
            port: 34543
            targetPort: 34543

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt
          acme.cert-manager.io/http01-edit-in-place: "false"
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: qbittorrent-credentials
          nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
          # nginx.ingress.kubernetes.io/auth-url: "http://qbittorrent-oauth2-proxy.media.svc.cluster.local/oauth2/auth"
          # nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: ${cloudflared_tunnel_uuid}.cfargotunnel.com
        hosts:
          - host: "torrent.${personal_domain}"
            paths:
              - path: "/"
        tls:
          - hosts:
              - "torrent.${personal_domain}"
            secretName: torrent.${personal_domain}-tls

    persistence:
      data:
        enabled: true
        existingClaim: qbittorrent-data-nas
        subPath:
          - path: config
            mountPath: /config

      media:
        enabled: true
        existingClaim: nas-volume1-media

    resources:
      requests:
        cpu: 200m
      limits:
        memory: 6Gi
      # nodeSelector:
      #   kubernetes.io/hostname: cameraman
      # ---
      # apiVersion: helm.toolkit.fluxcd.io/v2beta1
      # kind: HelmRelease
      # metadata:
      #   name: qbittorrent-oauth2-proxy
      #   namespace: media
      # spec:
      #   targetNamespace: media
      #   releaseName: qbittorrent-oauth2-proxy
      #   chart:
      #     spec:
      #       chart: oauth2-proxy
      #       version: "6.0.1"
      #       sourceRef:
      #         kind: HelmRepository
      #         name: oauth2-proxy
      #         namespace: flux-system
      #   interval: 2m0s
      #   values:
      #     replicaCount: 1
      #     extraArgs:
      #       provider: github
      #       github-org: "${blog_name}"
      #       github-team: "super-admins,qbittorrent"
      #       cookie-expire: 168h0m0s
#     config:
#       existingSecret: qbittorrent-oauth2-proxy
