apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-metrics-adapter
  namespace: flux-system
spec:
  targetNamespace: kube-system
  chart:
    spec:
      chart: kube-metrics-adapter
      version: "0.1.12"
      sourceRef:
        kind: HelmRepository
        name: tyzbit
        namespace: flux-system
  interval: 2m0s
  values:
    registry:
      image: registry.opensource.zalan.do/teapot/kube-metrics-adapter
      imageTag: v0.1.17
    enableCustomMetricsApi: true
    enableExternalMetricsApi: true
