apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: wordpress
  namespace: flux-system
spec:
  secretRef:
    name: docker-hub
  image: docker.io/bitnami/wordpress
  interval: 5m0s
