apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dri-pvc
  namespace: hotboxfort
spec:
  volumeName: dri-pvc-games
  accessModes: 
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 256Mi
