apiVersion: v1
kind: Service
metadata:
  name: qdirstat
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: qdirstat
  ports:
    - name: tcp
      protocol: TCP
      port: 5800
      targetPort: 5800
