apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner-nas
  namespace: flux-system
spec:
  targetNamespace: kube-system
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.17"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  interval: 2m0s
  values:
    fullnameOverride: nfs-provisioner-nas
    image: # Remove me when > 4.0.17 releases
      repository: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner # Remove me when > 4.0.17 releases
    storageClass:
      name: nas
      pathPattern: "$${.PVC.namespace}-$${.PVC.name}"
    nfs:
      server: nas.jura
      path: /volume1/cluster_storage
