apiVersion: v1
kind: Service
metadata:
  name: public-services
  namespace: personal
spec:
  selector:
    app: public-service
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
