apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m

  wait: false
  prune: false

  path: "./clusters/corpus/core-system/apps/networking/ingress-nginx"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
