# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.1/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: go-discord-modtools
  namespace: flux-system
spec:
  releaseName: go-discord-modtools
  targetNamespace: personal
  chart:
    spec:
      chart: app-template
      version: "3.2.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 2m0s
  values:
    controllers:
      go-discord-modtools:
        replicas: 0
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          go-discord-modtools:
            image:
              repository: ghcr.io/tyzbit/go-discord-modtools
              tag: "0.2.3" # {"$imagepolicy": "flux-system:go-discord-modtools:tag"}
            envFrom:
              - secretRef:
                  name: go-discord-modtools
            probes:
              liveness:
                enabled: true
                custom: true
                spec: &spec
                  httpGet:
                    port: 8080
                    path: /healthcheck
                  failureThreshold: 3
                  periodSeconds: 2
                  successThreshold: 1
                  timeoutSeconds: 5
              readiness:
                enabled: true
                custom: true
                spec: *spec
              startup:
                enabled: true
                custom: true
                spec:
                  !!merge <<: *spec
                  failureThreshold: 15
                  initialDelaySeconds: 5
            resources:
              requests:
                cpu: "50m"
              limits:
                memory: "256Mi"
    service:
      main:
        controller: main
        enabled: false
