apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-volume-cleanup-script
  namespace: kube-system
data:
  # double dollar signs is because flux does variable substitution
  cleanup.sh: |
    tail -n 0 -f /host/var/log/syslog | 
    grep 'orphaned pod' | 
    grep -Eow '\\w{8}-\\w{4}-\\w{4}-\\w{4}-\\w{12}' | 
    while read pod; do
      podvolumes="/host/var/lib/kubelet/pods/$$pod/volumes/"
      foundvolumes=$$("find "$${podvolumes}" -type d -maxdepth 1 -mindepth 1")
      if [[ $$(echo "$${foundvolumes}" | wc -l) -gt 0 ]]; then
        echo "removing folders:\\n$${foundvolumes}"
        echo "$${foundvolumes}" | while read dir; do
          echo "rm -rf $${dir}"
        done
      fi
    done
