apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: go-discord-archiver-dev-db
  namespace: flux-system
spec:
  releaseName: go-discord-archiver-dev-db
  targetNamespace: personal
  chart:
    spec:
      chart: app-template
      version: "1.5.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  interval: 2m0s
  values:
    image:
      repository: mariadb
      tag: 10.8

    command:
      - bash
      - -c
      - |
        mariadb-dump -h go-discord-archiver-db --password="$(MARIADB_PROD_ROOT_PASSWORD)" go_archiver > /backup/dump.sql && \
        while [[ $(mariadb -uroot --password="$${MARIADB_ROOT_PASSWORD}" "$${MARIADB_DATABASE}" < /backup/dump.sql; echo $?) != 0 ]]; do
          sleep 1
        done &
        exec docker-entrypoint.sh mariadbd

    envFrom:
      - secretRef:
          name: go-discord-archiver-dev-db

    controller:
      type: statefulset
      replicas: 1

    persistence:
      data:
        enabled: true
        type: emptyDir
        mountPath: /var/lib/mysql
      backup:
        enabled: true
        type: emptyDir

    podAnnotations:
      reloader.stakater.com/auto: "true"

    service:
      main:
        enabled: true
        type: NodePort
        ports:
          http:
            enabled: false
          sql:
            port: 3306
            nodePort: 30306

    resources:
      requests:
        cpu: 10m
      limits:
        memory: 512Mi
