apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: home-automation
data:
  config.yml: |
    logger:
      default: info
      # logs:
      #   frigate.record: debug
    database:
      path: /db/frigate.db
    mqtt:
      host: mosquitto
    record:
      enabled: True
      retain:
        days: 1
      events:
        retain:
          default: 30
          mode: active_objects
    snapshots:
      enabled: True
      retain:
        default: 30
        objects:
          person: 365
    objects:
      track:
        - person
    birdseye:
      enabled: True
      # objects, motion, continuous
      mode: continuous
    ffmpeg:
      # hwaccel_args: ["-hwaccel", "vaapi", "-hwaccel_device", "/dev/dri/renderD128", "-hwaccel_output_format", "yuv420p"]
      hwaccel_args: preset-vaapi
      input_args: preset-rtsp-restream
    # go2rtc is disabled because frigate kept running out of memory and also 404ing
    # go2rtc:
    #   streams:
    #     frontdoor: 'rtsp://{FRIGATE_FRONTDOOR_CREDENTIALS}@frontdoor:554'
    #     backdoor: 'rtsp://{FRIGATE_BACKDOOR_CREDENTIALS}@backdoor:554/live'
    #     driveway: 'rtsp://{FRIGATE_DRIVEWAY_CREDENTIALS}@driveway:554/live'
    #     porch: 'rtsp://{FRIGATE_PORCH_CREDENTIALS}@porch:554/live'
    #     court: 'rtsp://{FRIGATE_COURT_CREDENTIALS}@court:554/live'

    detectors:
      coral:
        type: edgetpu
        device: usb

    cameras:
      frontdoor:
        motion:
          mask:
            - 0,390,193,302,416,250,613,202,707,193,1021,155,1149,113,1138,0,0,0
        objects:
          filters:
            person:
              mask:
                - 0,390,193,302,416,250,613,202,707,193,1021,155,1149,113,1138,0,0,0
        ffmpeg:
          inputs:
            # - path: 'rtsp://localhost:8554/frontdoor'
            - path: 'rtsp://{FRIGATE_FRONTDOOR_CREDENTIALS}@TV-IP302PI:554'
              roles:
                - detect
                - restream # enabled by default
        detect:
          width: 1280
          height: 720
          fps: 5
        mqtt:
          height: 540

      backdoor:
        ffmpeg:
          inputs:
            # - path: 'rtsp://localhost:8554/backdoor'
            - path: 'rtsp://{FRIGATE_BACKDOOR_CREDENTIALS}@backdoor:554/live'
              roles:
                - detect
                - restream # enabled by default
        motion:
          mask:
            - 480,176,791,187,1104,210,1567,289,1810,345,1920,356,1920,0,0,0,0,254
        objects:
          filters:
            person:
              # min_score: 0.80
              threshold: 0.80
              mask: 
              - 480,176,791,187,1104,210,1567,289,1810,345,1920,356,1920,0,0,0,0,254
        detect:
          width: 1920
          height: 1080
          fps: 5
        mqtt:
          height: 540

      driveway:
        ffmpeg:
          inputs:
            # - path: 'rtsp://localhost:8554/driveway'
            - path: 'rtsp://{FRIGATE_DRIVEWAY_CREDENTIALS}@driveway:554/live'
              roles:
                - detect
                - restream # enabled by default
        motion:
          mask:
            - 1920,0,1920,356,1920,1080,1539,1080,1697,838,1789,460,1788,248,1715,151,1510,38,1394,22,1198,119,1104,88,1176,0
            - 137,842,50,606,202,366,497,526,528,657
        objects:
          filters:
            person:
              # min_score: 0.72
              mask: 
                - 1920,0,1920,356,1920,1080,1539,1080,1697,838,1789,460,1788,248,1715,151,1510,38,1394,22,1198,119,1104,88,1176,0
                - 137,842,50,606,202,366,497,526,528,657
        detect:
          width: 1920
          height: 1080
          fps: 5
        mqtt:
          height: 540

      porch:
        ffmpeg:
          inputs:
            # - path: 'rtsp://localhost:8554/porch'
            - path: 'rtsp://{FRIGATE_PORCH_CREDENTIALS}@AMC047AD_C51725:554/live'
              roles:
                - detect
                - restream # enabled by default
        motion:
          mask:
            - 2688,1520,1950,1520,2168,751,2688,738
        objects:
          filters:
            person:
              # min_score: 0.73
              mask:
                - 2688,1520,1950,1520,2168,751,2688,738
        detect:
          width: 2688
          height: 1520
          fps: 5
        mqtt:
          height: 540

      court:
        ffmpeg:
          inputs:
            # - path: 'rtsp://localhost:8554/court'
            - path: 'rtsp://{FRIGATE_COURT_CREDENTIALS}@AMC057A3_C3DED9:554/live'
              roles:
                - detect
        snapshots:
          enabled: False
        detect:
          width: 1920
          height: 1080
          fps: 5
