apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: home-automation
data:
  config.yml: |
    logger:
      default: info
      # logs:
      #   frigate.record: debug
    database:
      path: /db/frigate.db
    mqtt:
      host: mosquitto
    record:
      enabled: True
      retain:
        days: 1
      events:
        retain:
          default: 30
          mode: active_objects
    snapshots:
      enabled: True
      retain:
        default: 30
        objects:
          person: 365
    objects:
      track:
        - person
    birdseye:
      enabled: True
      # objects, motion, continuous
      mode: continuous
    # go2rtc:
    #   streams:
    #     frontdoor:
    #       - 'rtsp://{FRIGATE_FRONTDOOR_CREDENTIALS}@frontdoor:554'
    #     backdoor:
    #       - 'rtsp://{FRIGATE_BACKDOOR_CREDENTIALS}@backdoor:554/live'
    #     driveway:
    #       - 'rtsp://{FRIGATE_DRIVEWAY_CREDENTIALS}@driveway:554/live'
    #     porch:
    #       - 'rtsp://{FRIGATE_PORCH_CREDENTIALS}@porch:554/live'
    #     court:
    #       - 'rtsp://{FRIGATE_COURT_CREDENTIALS}@court:554/live'
    detectors:
      coral:
        type: edgetpu
        device: usb

    cameras:
      frontdoor:
        motion:
          mask:
            - 0,390,193,302,416,250,613,202,707,193,1021,155,1149,113,1138,0,0,0
        objects:
          filters:
            person:
              mask:
                - 0,390,193,302,416,250,613,202,707,193,1021,155,1149,113,1138,0,0,0
        ffmpeg:
          hwaccel_args: preset-vaapi
          input_args: preset-rtsp-restream
          inputs:
            # - path: 'rtsp://127.0.0.1:8554/frontdoor'
            - path: 'rtsp://{FRIGATE_FRONTDOOR_CREDENTIALS}@frontdoor:554'
              roles:
                - detect
                - restream # enabled by default
        detect:
          width: 1280
          height: 720
          fps: 5
        mqtt:
          height: 540

      backdoor:
        ffmpeg:
          hwaccel_args: preset-vaapi
          input_args: preset-rtsp-restream
          inputs:
            # - path: 'rtsp://127.0.0.1:8554/backdoor'
            - path: 'rtsp://{FRIGATE_BACKDOOR_CREDENTIALS}@backdoor:554/live'
              roles:
                - detect
                - restream # enabled by default
        motion:
          mask:
            - 480,176,791,187,1104,210,1567,289,1810,345,1920,356,1920,0,0,0,0,254
        objects:
          filters:
            person:
              min_score: 0.80
              mask: 
              - 480,176,791,187,1104,210,1567,289,1810,345,1920,356,1920,0,0,0,0,254
        detect:
          width: 1920
          height: 1080
          fps: 5
        mqtt:
          height: 540

      driveway:
        ffmpeg:
          hwaccel_args: preset-vaapi
          input_args: preset-rtsp-restream
          inputs:
            # - path: 'rtsp://127.0.0.1:8554/driveway'
            - path: 'rtsp://{FRIGATE_DRIVEWAY_CREDENTIALS}@driveway:554/live'
              roles:
                - detect
                - restream # enabled by default
        motion:
          mask:
            - 1920,0,1920,356,1920,1080,1539,1080,1697,838,1796,386,1812,268,1699,176,1482,60,1410,71,1266,166,1170,119,1176,0
            - 180,838,190,579,298,394,604,563,612,745
        objects:
          filters:
            person:
              # min_score: 0.72
              mask: 
                - 1920,0,1920,356,1920,1080,1539,1080,1697,838,1796,386,1812,268,1699,176,1482,60,1410,71,1266,166,1170,119,1176,0
                - 180,838,190,579,298,394,604,563,612,745
        detect:
          width: 1920
          height: 1080
          fps: 5
        mqtt:
          height: 540

      porch:
        ffmpeg:
          hwaccel_args: preset-vaapi
          input_args: preset-rtsp-restream
          inputs:
            # - path: 'rtsp://127.0.0.1:8554/porch'
            - path: 'rtsp://{FRIGATE_PORCH_CREDENTIALS}@porch:554/live'
              roles:
                - detect
                - restream # enabled by default
        motion:
          mask:
            - 2688,1520,1950,1520,2168,751,2688,738
        objects:
          filters:
            person:
              # min_score: 0.73
              mask:
                - 2688,1520,1950,1520,2168,751,2688,738
        detect:
          width: 2688
          height: 1520
          fps: 5
        mqtt:
          height: 540

      court:
        ffmpeg:
          input_args: preset-rtsp-restream
          inputs:
            # - path: 'rtsp://127.0.0.1:8554/court'
            - path: 'rtsp://{FRIGATE_COURT_CREDENTIALS}@court:554/live'
              roles:
                - detect
        snapshots:
          enabled: False
        detect:
          width: 1920
          height: 1080
          fps: 5
