apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: home-automation
data:
  config.yml: |
    logger:
      default: info
      # logs:
      #   frigate.record: debug
    database:
      path: /db/frigate.db
    mqtt:
      host: mosquitto
    record:
      enabled: True
      retain:
        days: 1
      events:
        retain:
          default: 30
          mode: active_objects
    snapshots:
      enabled: True
      retain:
        default: 30
        objects:
          person: 365
    objects:
      track:
        - person
    birdseye:
      enabled: True
      # objects, motion, continuous
      mode: continuous
    restream:
      enabled: True
      birdseye: True
      # jsmpeg:
        # height: 720
        # quality: 8
    detectors:
      coral:
        type: edgetpu
        device: usb

    cameras:
      frontdoor:
        motion:
          mask:
            - 0,390,190,281,413,219,612,181,842,131,1149,113,1138,0,0,0
        ffmpeg:
          hwaccel_args: preset-intel-vaapi
          inputs:
            - path: 'rtsp://{FRIGATE_FRONTDOOR_CREDENTIALS}@frontdoor:554'
              roles:
                - detect
                - restream # enabled by default
        detect:
          width: 1280
          height: 720
          fps: 5
        mqtt:
          height: 540

      backdoor:
        ffmpeg:
          hwaccel_args: preset-intel-vaapi
          inputs:
            - path: 'rtsp://{FRIGATE_BACKDOOR_CREDENTIALS}@backdoor:554/live'
              roles:
                - detect
                - restream # enabled by default
        motion:
          mask:
            - 480,176,791,187,1104,210,1567,289,1810,345,1920,356,1920,0,0,0,0,254
        objects:
          filters:
            person:
              # min_score: 0.72
              mask: 
              - 480,176,791,187,1104,210,1567,289,1810,345,1920,356,1920,0,0,0,0,254
        detect:
          width: 1920
          height: 1080
          fps: 5
        mqtt:
          height: 540

      driveway:
        ffmpeg:
          hwaccel_args: preset-intel-vaapi
          inputs:
            - path: 'rtsp://{FRIGATE_DRIVEWAY_CREDENTIALS}@driveway:554/live'
              roles:
                - detect
                - restream # enabled by default
        motion:
          mask:
            - 1848,337,1605,1080,1920,1080,1920,252,1920,0,1885,0
            - 720,430,318,742,282,696,251,595,403,493,615,339
        objects:
          filters:
            person:
              # min_score: 0.72
              mask: 
              - 1848,337,1605,1080,1920,1080,1920,252,1920,0,1885,0
              - 720,430,318,742,282,696,251,595,403,493,615,339
        detect:
          width: 1920
          height: 1080
          fps: 5
        mqtt:
          height: 540

      porch:
        ffmpeg:
          hwaccel_args: preset-intel-vaapi
          inputs:
            - path: 'rtsp://{FRIGATE_PORCH_CREDENTIALS}@porch:554/live'
              roles:
                - detect
                - restream # enabled by default
        motion:
          mask:
            - 2688,1520,1950,1520,2168,751,2688,738
        objects:
          filters:
            person:
              # min_score: 0.73
              mask:
                - 2688,1520,1950,1520,2168,751,2688,738
        detect:
          width: 2688
          height: 1520
          fps: 5
        mqtt:
          height: 540

      court:
        ffmpeg:
          inputs:
            - path: 'rtsp://{FRIGATE_COURT_CREDENTIALS}@court:554/live'
              roles:
                - detect
        snapshots:
          enabled: False
        detect:
          width: 1920
          height: 1080
          fps: 5

  frigate-go2rtc.yml: |
    webrtc:
      listen: ":8555"
      candidates:
        - stun:8555
