apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: frigate
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frigate
  filterTags:
    pattern: '^(?P<semver>[0-9]+\.[0-9]+\.[0-9]+)(-[a-z]+(?P<prerelease>[0-9]+))?$'
    extract: "$semver$prerelease"
  policy:
    semver:
      range: "~0.12"
