apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: go-discord-archiver
  namespace: flux-system
spec:
  releaseName: go-discord-archiver
  targetNamespace: personal
  chart:
    spec:
      chart: app-template
      version: "1.4.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  interval: 2m0s
  values:
    image:
      repository: docker.io/tyzbit/go-discord-archiver
      tag: 2.5.1 # {"$imagepolicy": "flux-system:go-discord-archiver:tag"}

    envFrom:
      - secretRef:
          name: go-discord-archiver

    probes:
      custom: true
      spec:
        livenessProbe: &probe
          failureThreshold: 3
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            port: 8080
            path: /healthcheck
        readinessProbe:
          !!merge <<: *probe
        startupProbe:
          !!merge <<: *probe
          failureThreshold: 15
          initialDelaySeconds: 5

    podAnnotations:
      reloader.stakater.com/auto: "true"

    resources:
      requests:
        cpu: "50m"
      limits:
        memory: "256Mi"
