apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: ${cloudflared_tunnel_uuid}
    credentials-file: /etc/cloudflared/cred.json
    originRequest:
      connectTimeout: 30s
      noTLSVerify: true
    warp-routing:
      enabled: false

    ingress:
      - hostname: mux.${neko_domain}
        service: tcp://neko.media:5100
      - hostname: mux.${hotboxfort_domain}
        service: tcp://neko.hotboxfort:5100
      - hostname: mux.${sheanxious_domain}
        service: tcp://neko.sheanxious:5100
      - service: https://kube-system-ingress-nginx-controller.kube-system
