apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: ${cloudflare_tunnel_uuid}
    originRequest:
      noTLSVerify: true

    ingress:
      - service: https://kube-system-ingress-nginx-controller.kube-system
