---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cloudflared
  namespace: *app
spec:
  releaseName: *app
  targetNamespace: *app
  interval: 2m0s
  chart:
    spec:
      chart: app-template
      version: "1.3.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    global:
      nameOverride: *app
    controller:
      type: daemonset
    image:
      repository: cloudflare/cloudflared
      tag: 2023.3.1-amd64
    args:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${cloudflared_token}
    persistence:
      # config:
      #   enabled: true
      #   type: custom
      #   volumeSpec:
      #     configMap:
      #       name: &config cloudflare-tunnel
      #   subPath:
      #     - path: config.yaml
      #       mountPath: /etc/cloudflared/config.yaml
      #       readOnly: true
    resources:
      requests:
        memory: 64Mi
        cpu: 10m
      limits:
        memory: 128Mi
    podAnnotations:
      reloader.stakater.com/auto: "true"
    service:
      main:
        enabled: false
    ingress:
      main:
        enabled: false
