apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-discord-archiver
  namespace: personal
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-discord-archiver
  template:
    metadata:
      labels:
        app: go-discord-archiver
    spec:
      containers:
      - name: go-discord-archiver
        image: docker.io/tyzbit/go-discord-archiver:0.1.2 # {"$imagepolicy": "flux-system:go-discord-archiver"}
        envFrom:
        - secretRef:
            name: go-discord-archiver
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "16Mi"
      imagePullSecrets:
      - name: docker-hub
