apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: go-discord-archiver
  namespace: flux-system
spec:
  secretRef:
    name: docker-hub
  image: docker.io/tyzbit/go-discord-archiver
  interval: 2m0s
