apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketchat-longhorn-webapp
  namespace: rocketchat-${chat_name}-chat
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: longhorn-webapp
  accessModes:
    - ReadWriteOnce
