apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-discord-amputator
  namespace: personal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-discord-amputator
  template:
    metadata:
      labels:
        app: go-discord-amputator
    spec:
      containers:
      - name: go-discord-amputator
        image: docker.io/tyzbit/go-discord-amputator:0.3.0 # {"$imagepolicy": "flux-system:go-discord-amputator"}
        envFrom:
        - secretRef:
            name: go-discord-amputator
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "16Mi"
      imagePullSecrets:
      - name: docker-hub
