apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-discord-amputator-mariadb-longhorn-database
  namespace: personal
spec:
  accessModes: 
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn-database
  resources:
    requests:
      storage: 1Gi
