apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m

  wait: false
  prune: true

  path: "./clusters/workbench/apps/core-system/networking/cert-manager/app"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
