apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 10s
  timeout: 5m

  wait: false
  prune: true

  path: "./clusters/corpus/core-system/storage/longhorn"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn: [{ name: kubernetes-secrets }]
