apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: wordpress-hotboxfort
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: wordpress
  policy:
    semver:
      range: "~ 5.9"
