apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ${game_name}-stream
  namespace: flux-system
spec:
  releaseName: ${game_name}-stream
  targetNamespace: media
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 2m0s
  values:
    image:
      # results in a blank screen
      # repository: ghcr.io/m1k1o/neko/intel-firefox
      repository: tiangolo/nginx-rtmp
      tag: latest-2024-03-25

    controller:
      type: deployment
      replicas: 1

    persistence:
      config:
        enabled: true
        name: ${game_name}-stream-config
        type: configMap
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
        readOnly: true
        defaultMode: 0755
      media:
        enabled: true
        type: emptyDir

    podAnnotations:
      reloader.stakater.com/auto: "true"

    resources:
      requests:
        cpu: 10m

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 80
            targetPort: 80
          rtmp:
            port: &port 1935
            targetPort: *port
          # rtmp-udp:
          #   port: *port
          #   targetPort: *port
          #   protocol: UDP

    probes:
      readiness: &probe
        enabled: false
      liveness: *probe
      startup: *probe

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          acme.cert-manager.io/http01-edit-in-place: "true"
          # nginx.ingress.kubernetes.io/proxy-buffer-size: "128m"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
          # nginx.ingress.kubernetes.io/proxy-buffering: "off"
          # nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: ${cloudflared_tunnel_uuid}.cfargotunnel.com
        hosts:
          - host: vr.${game_domain}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: vr.${game_domain}-tls
            hosts:
              - vr.${game_domain}
