apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  wait: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  resources:
    - helmrelease.yaml
  # dependsOn:
  #   - name: kubernetes-secrets
  #     kind: Kustomization
  #     version: v1
  #     fieldName: metadata.name
