apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ${neko_name}-neko
  namespace: flux-system
spec:
  releaseName: ${neko_name}-neko
  targetNamespace: media
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 2m0s
  valuesFrom:
    - kind: Secret
      name: ${neko_name}-neko
  values:
    image:
      # results in a blank screen
      # repository: ghcr.io/m1k1o/neko/intel-firefox
      repository: ghcr.io/m1k1o/neko/firefox
      tag: 2.8.11

    env:
      NEKO_SCREEN: 1280x720@30
      NEKO_PROXY: "true"
      NEKO_TCPMUX: &mux "5100"
      NEKO_UDPMUX: *mux
      NEKO_ICELITE: "true"
      NEKO_HWENC: vaapi
      NEKO_VIDEO: >-
        ximagesrc display-name=%s show-pointer=true use-damage=false
        ! video/x-raw,framerate=30/1
        ! videoconvert 
        ! queue 
        ! video/x-raw,format=NV12 
        ! x264enc 
          threads=4 
          bitrate=3500 
          key-int-max=60 
          vbv-buf-capacity=4000 
          byte-stream=true 
          tune=zerolatency 
          speed-preset=veryfast 
        ! video/x-h264,stream-format=byte-stream,profile=constrained-baseline
        ! rtph264pay name=pay0 pt=96

    controller:
      type: statefulset
      replicas: 1

    persistence:
      config:
        enabled: true
        name: neko-firefox-config
        type: configMap
        mountPath: /usr/lib/firefox/distribution/policies.json
        subPath: policies.json
        readOnly: true
        defaultMode: 0755
      profile:
        enabled: true
        existingClaim: neko-firefox-profile-nas
        mountPath: /home/neko/.mozilla/firefox/profile.default
      dri:
        enabled: true
        type: hostPath
        hostPath: &dri /dev/dri
        mountPath: *dri
      shm:
        enabled: true
        type: hostPath
        hostPath: &shm /dev/shm
        mountPath: *shm

    # podSecurityContext:
    #   supplementalGroups: [44, 109, 10000]

    # securityContext:
    #   privileged: true

    podAnnotations:
      reloader.stakater.com/auto: "true"

    resources:
      requests:
        cpu: 1000m

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            port: 80
            targetPort: 8080
          mux:
            port: &port 5100
            targetPort: *port
          video1:
            port: &rtsp 8554
            targetPort: *rtsp
          muxudp:
            port: *port
            targetPort: *port
            protocol: UDP
          video2:
            port: *rtsp
            targetPort: *rtsp
            protocol: UDP

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          acme.cert-manager.io/http01-edit-in-place: "true"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.alpha.kubernetes.io/target: ${home_domain_ddns}
        hosts:
          - host: ${neko_domain}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: ${neko_domain}-tls
            hosts:
              - ${neko_domain}
