apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ${neko_name}-neko-nginx
  namespace: flux-system
spec:
  releaseName: ${neko_name}-neko-nginx
  targetNamespace: media
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 2m0s
  values:
    image:
      # results in a blank screen
      # repository: ghcr.io/m1k1o/neko/intel-firefox
      repository: tiangolo/nginx-rtmp
      tag: latest-2024-03-25

    controller:
      type: deployment
      replicas: 1

    podAnnotations:
      reloader.stakater.com/auto: "true"

    resources:
      requests:
        cpu: 10m

    service:
      main:
        enabled: true
        type: NodePort
        ports:
          http:
            port: 80
            targetPort: 80
          mux:
            port: &port 1935
            targetPort: *port
          muxudp:
            port: *port
            targetPort: *port
            protocol: UDP

    probes:
      readiness: &probe
        enabled: false
      liveness: *probe
      startup: *probe

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          acme.cert-manager.io/http01-edit-in-place: "true"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.alpha.kubernetes.io/target: ${home_domain_ddns}
        hosts:
          - host: rtmp.${neko_domain}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: ${neko_domain}-tls
            hosts:
              - ${neko_domain}
