apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ${neko_name}-neko-nginx
  namespace: flux-system
spec:
  releaseName: ${neko_name}-neko-nginx
  targetNamespace: media
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 2m0s
  values:
    image:
      # results in a blank screen
      # repository: ghcr.io/m1k1o/neko/intel-firefox
      repository: tiangolo/nginx-rtmp
      tag: latest-2024-03-25

    controller:
      type: deployment
      replicas: 1

    persistence:
      config:
        enabled: true
        name: neko-nginx-rtmp-config
        type: configMap
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
        readOnly: true
        defaultMode: 0755

    podAnnotations:
      reloader.stakater.com/auto: "true"

    resources:
      requests:
        cpu: 10m

    service:
      main:
        enabled: true
        type: ClusterIP
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: false
          rtmp:
            port: &port 1935
            targetPort: *port
          # rtmp-udp:
          #   port: *port
          #   targetPort: *port
          #   protocol: UDP

    probes:
      readiness: &probe
        enabled: false
      liveness: *probe
      startup: *probe
