apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: flux-system
spec:
  targetNamespace: media
  chart:
    spec:
      chart: app-template
      version: "1.3.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  interval: 2m0s
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.32.5
    fullnameOverride: overseerr

    controller:
      replicas: 1 # active longhorn-webapp

    podSecurityContext:
      fsGroup: 568

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            port: 5055
            targetPort: 5055

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt
          acme.cert-manager.io/http01-edit-in-place: "false"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.alpha.kubernetes.io/target: ${personal_domain_ddns}
        hosts:
          - host: &host "request.${blog_domain}"
            paths:
              - path: "/"
        tls:
          - hosts:
              - *host
            secretName: *host

    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config-longhorn-webapp
        mountPath: /app/config
    # resources:
    #   requests:
    #     cpu: 200m
    #   limits:
    #     memory: 6Gi
    # nodeSelector:
    #   kubernetes.io/hostname: cameraman
