apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grav-${anime_blog_name}
  namespace: flux-system
spec:
  targetNamespace: personal
  chart:
    spec:
      chart: grav
      version: "0.7.0"
      sourceRef:
        kind: HelmRepository
        name: tyzbit
        namespace: flux-system
  interval: 2m0s
  values:
    fullnameOverride: grav-${anime_blog_name}
    grav:
      image:
        repository: dsavell/inspector
        tag: admin-1.7.39.4-20230311 # {"$imagepolicy": "flux-system:grav-${anime_blog_name}:tag"}
        pullPolicy: Always
      config:
        #   DUID: "1000"
        #   DGID: "1000"
        #   GRAV_MULTISITE: subdirectory
        NGINX_CLIENT_MAX_BODY_SIZE: 256m
    filebrowser:
      enabled: true
      image:
        pullPolicy: Always
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - personal-grav-${anime_blog_name}
              topologyKey: kubernetes.io/hostname
    persistence:
      enabled: true
      existingClaimName: grav-${anime_blog_name}-data-longhorn-webapp
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    statefulSetAnnotations:
      reloader.stakater.com/auto: "true"
    imagePullSecrets:
      - name: docker-hub
    ingress:
      enabled: true
      className: nginx
      annotations:
        acme.cert-manager.io/http01-edit-in-place: "false"
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/target: ${anime_blog_domain_ddns}
        nginx.ingress.kubernetes.io/proxy-body-size: 256m
      labels:
        use-cloudflare-dns-solver: "true"
      hosts:
        - host: ${anime_blog_domain}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: ${anime_blog_domain}-tls
          hosts:
            - ${anime_blog_domain}
            - "*.${anime_blog_domain}"
