apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neko
  namespace: flux-system
spec:
  targetNamespace: media
  chart:
    spec:
      chart: neko
      version: "0.4.1"
      sourceRef:
        kind: HelmRepository
        name: tyzbit
        namespace: flux-system
  interval: 2m0s
  values:
    env:
      NEKO_PROXY: "true"
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: media-neko
      type: LoadBalancer
      loadBalancerIP: 192.168.1.74
      port: 80
    # securityContext:
    #   privileged: true
    # persistence:
    #   dri:
    #     existingClaim: dri-pvc
    #     path: /dev/dri
    existingSecret: neko
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
        acme.cert-manager.io/http01-edit-in-place: "false"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/target: ${cloudflared_tunnel_uuid}.cfargotunnel.com
        nginx.ingress.kubernetes.io/server-snippets: |
          location / {
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
              proxy_read_timeout 86400;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $remote_addr;
              proxy_set_header X-Forwarded-Host $host;
              proxy_set_header X-Forwarded-Port $server_port;
              proxy_set_header X-Forwarded-Protocol $scheme;
            }
      hosts:
        - host: ${neko_domain}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: ${neko_domain}-tls
          hosts:
            - ${neko_domain}
    resources:
      requests:
        cpu: 1000m
