apiVersion: v1
kind: Service
metadata:
  name: iperf3-server
  namespace: personal
spec:
  type: ClusterIP
  selector:
    app: iperf3-server
  ports:
    - name: tcp
      protocol: TCP
      port: 5201
      targetPort: 5201
    - name: udp
      protocol: UDP
      port: 5201
      targetPort: 5201
