apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: corpus-control-plane
  namespace: networking
  labels:
    kubernetes.io/service-name: corpus-control-plane
addressType: IPv4
ports:
  - name: k8s
    port: 6443
    protocol: TCP
endpoints:
  - addresses:
      - "192.168.1.21"
      - "192.168.1.22"
      - "192.168.1.23"
