apiVersion: v1
kind: Service
metadata:
  name: corpus-control-plane
  namespace: networking
spec:
  type: NodePort
  selector:
    app: corpus-control-plane
  ports:
    - port: 3443
      nodePort: 34443
