apiVersion: v1
kind: Service
metadata:
  name: corpus-control-plane
  namespace: networking
spec:
  type: NodePort
  ports:
    - name: k8s
      port: 6443
      protocol: TCP
      targetPort: 6443
      nodePort: 32443
