apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogger-grab-control
  namespace: personal
  labels:
    app: blogger-grab-control
spec:
  replicas: 80
  selector:
    matchLabels:
      app: blogger-grab-control
  template:
    metadata:
      labels:
        app: blogger-grab-control
    spec:
      containers:
        - name: blogger-grab-control
          image: atdr.meo.ws/archiveteam/blogger-grab
          env:
            - name: SHARED_RSYNC_THREADS
              value: "2"
          args:
            - "--concurrent"
            - "20"
            - "--disable-web-server"
            - "tyzbit"
          volumeMounts:
            - mountPath: /grab/data
              name: cache-volume
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: 4096Mi
          imagePullPolicy: Always
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
