apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app blogger-grab
  namespace: personal
  labels:
    app: *app
spec:
  replicas: 20
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "PreferNoSchedule"
    spec:
      containers:
        - name: *app
          image: atdr.meo.ws/archiveteam/blogger-grab
          env:
            - name: SHARED_RSYNC_THREADS
              value: "2"
          args:
            - "--concurrent"
            - "20"
            - "--disable-web-server"
            - "tyzbit"
          volumeMounts:
            - mountPath: /grab/data
              name: cache-volume
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: 4096Mi
          imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: "myocyte4-kpkjn"
    # affinity:
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - topologyKey: "kubernetes.io/hostname"
    #         labelSelector:
    #           matchExpressions:
    #             - key: app.kubernetes.io/name
    #               operator: In
    #               values:
    #                 - "plex"
    #                 - "plex-secondary"
