apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app blogger-grab
  namespace: personal
  labels:
    app: *app
spec:
  replicas: 12
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "PreferNoSchedule"
    spec:
      containers:
        - name: *app
          image: atdr.meo.ws/archiveteam/blogger-grab@sha256:c803d93730810a3b96fde6b77cda65e2dc1aca7092bd45831280cee9066af5a3
          env:
            - name: SHARED_RSYNC_THREADS
              value: "2"
          args:
            - --concurrent
            - "20"
            - --disable-web-server
            - tyzbit
          volumeMounts:
            - mountPath: /grab/data
              name: cache-volume
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: 4096Mi
          imagePullPolicy: Always
      nodeSelector:
        blogger-node: "true"
    # affinity:
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - topologyKey: "kubernetes.io/hostname"
    #         labelSelector:
    #           matchExpressions:
    #             - key: app.kubernetes.io/name
    #               operator: In
    #               values:
    #                 - "plex"
    #                 - "plex-secondary"
