apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: revolt-${chat_name}-chat-minio-longhorn-static
  namespace: revolt-${chat_name}-chat
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 50Gi
