apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr
  namespace: flux-system
spec:
  releaseName: tdarr
  targetNamespace: media
  timeout: 2m
  interval: 2m0s
  chart:
    spec:
      chart: tdarr
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: haveagitgat/tdarr
      tag: 2.00.18.2
      pullPolicy: IfNotPresent
    controller:
      replicas: 1 # active longhorn-webapp nas
    nodeSelector:
      longhorn: primary
    env:
      TZ: America/New_York
    podSecurityContext:
      fsGroup: 568
      supplementalGroups:
        - 44
        - 109
    node:
      enabled: true
      id: node
      image:
        repository: haveagitgat/tdarr_node
        tag: 2.00.18.2
        pullPolicy: IfNotPresent
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - frigate
            topologyKey: "kubernetes.io/hostname"
    # initContainers:
    #   fixperms:
    #     name: fixperms
    #     image: busybox
    #     command:
    #     - sh
    #     - -c
    #     - chown 568:568 /config -R
    #     env:
    #     - name: TZ
    #       value: America/New_York
    #     volumeMounts:
    #     - name: config
    #       mountPath: /config
    persistence:
      config:
        enabled: true
        mountPath: /app/server
        existingClaim: tdarr-config-longhorn-webapp
      # nzb-downloads:
      #   enabled: true
      #   existingClaim: nzbget-downloads
      media:
        enabled: true
        existingClaim: nas-volume1-media
      dri:
        enabled: true
        mountPath: /dev/dri
        existingClaim: dri-pvc
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/auth-url: "http://tdarr-oauth2-proxy.media.svc.cluster.local/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
          cert-manager.io/cluster-issuer: letsencrypt
          acme.cert-manager.io/http01-edit-in-place: "false"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: ${personal_domain_ddns}
        hosts:
          - host: "transcode.${personal_domain}"
            paths:
              - path: "/"
        tls:
          - hosts:
              - "transcode.${personal_domain}"
            secretName: transcode.${personal_domain}-tls
      oauth:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: "transcode.${personal_domain}"
            paths:
              - path: "/oauth2"
                service:
                  name: tdarr-oauth2-proxy
                  port: 80
        tls:
          - hosts:
              - "transcode.${personal_domain}"
            secretName: transcode.${personal_domain}-tls
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr-oauth2-proxy
  namespace: media
spec:
  targetNamespace: media
  releaseName: tdarr-oauth2-proxy
  chart:
    spec:
      chart: oauth2-proxy
      version: "6.0.1"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  interval: 2m0s
  values:
    replicaCount: 1
    extraArgs:
      provider: github
      github-org: "${blog_name}"
      github-team: "super-admins,tdarr"
      cookie-expire: 168h0m0s
    config:
      existingSecret: tdarr-oauth2-proxy
