apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: flux-system
spec:
  releaseName: flaresolverr
  targetNamespace: media
  interval: 2m0s
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/flaresolverr/flaresolverr
      tag: v3.3.15

    controller:
      replicas: 1

    env:
      TZ: America/New_York

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            port: 8191
            targetPort: 8191
