apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flaresolverr
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m

  wait: false
  prune: true

  path: "./clusters/corpus/apps/media/flaresolverr"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
