apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: btc-balance-notifier
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 10s
  timeout: 5m

  wait: false
  prune: true

  path: "./clusters/corpus/apps/crypto/btc-balance-notifier"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn: [{ name: kubernetes-secrets }, { name: longhorn-recurring-jobs }]
  postBuild:
    substituteFrom:
      - kind: Secret
        name: sensitive-values
