apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-longhorn-plex
  namespace: media
spec:
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  storageClassName: longhorn-plex
  accessModes:
    - ReadWriteOnce
