apiVersion: v1
kind: ConfigMap
metadata:
  name: ytdl-sub-config
  namespace: media
data:
  config.yaml: |
    configuration:
      working_directory: "/tmp/ytdl-sub"
    presets:
      yt_video:
        download:
          download_strategy: "url"
        ytdl_options:
          format: "bestvideo[ext=webm][height<=1440]+bestaudio[ext=webm]/best[ext=webm]/best"
          ignoreerrors: True
          break_on_existing: True
          break_on_reject: True
          final_ext: mkv
          cachedir: "/tmp/ytdl-sub"
        file_convert:
          convert_to: "mkv"
        date_range:
          before: "{download_before}"
          after: "{download_after}"
        output_options:
          maintain_download_archive: True
          output_directory: "/media/youtube"
          file_name: "{video_path}.{ext}"
          thumbnail_name: "{video_path}-thumb.{thumbnail_ext}"
          keep_files_after: "{download_after}"
        overrides:
          video_name: "{upload_date} {title_sanitized}"
          video_type: "{channel}"
          video_path: "{video_type_sanitized}/{video_name}"
          download_before: "now"
          download_after: "19000101"
        nfo_tags:
          nfo_name: "{video_path}.nfo"
          nfo_root: "episodedetails"
          tags:
            title: "{title}"
            season: "{season}"
            episode: "{episode}"
            year: "{upload_year}"
            aired: "{upload_date_standardized}"
      yt_playlist:
        preset: "yt_video"
        output_options:
          output_directory: "/media/youtube/{tv_show_name_sanitized}"
          file_name: "{episode_path}.{ext}"
          thumbnail_name: "{episode_path}-thumb.{thumbnail_ext}"
        overrides:
          tv_show_name: "OVERRIDE IN SUBSCRIPTION"
          season: "{upload_year}"
          episode: "{upload_month}{upload_day_padded}"
          episode_padded: "{upload_month_padded}{upload_day_padded}"
          episode_file_name: "S{season}E{episode_padded} {title_sanitized}"
          episode_path: "Season {season}/{episode_file_name}"
        output_directory_nfo_tags:
          nfo_name: "tvshow.nfo"
          nfo_root: "tvshow"
          tags:
            title: "{tv_show_name}"
        nfo_tags:
          nfo_name: "{episode_path}.nfo"
          nfo_root: "episodedetails"
          tags:
            title: "{title}"
            season: "{season}"
            episode: "{episode}"
            year: "{upload_year}"
            aired: "{upload_date_standardized}"
      yt_channel:
        preset: "yt_playlist"
        download:
          download_strategy: "url"
          playlist_thumbnails:
            - name: "official-poster.jpg"
              uid: "avatar_uncropped"
            - name: "official-banner.jpg"
              uid: "banner_uncropped"
        match_filters:
          filters:
            - "original_url!*=/shorts/"
            - "!is_live"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ytdl-sub-subscriptions
  namespace: media
data:
  subscriptions.yaml: |
    reol:
      preset: "yt_playlist"
      download:
        url: "https://www.youtube.com/playlist?list=PLWh_Fb1QWWg1BuddtCQt9XsziVUjtr1ui"
      overrides:
        tv_show_name: Reol
