apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ytdl-sub
  namespace: flux-system
spec:
  releaseName: ytdl-sub
  targetNamespace: media
  timeout: 15m
  interval: 2m0s
  chart:
    spec:
      chart: app-template
      version: "1.3.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    image:
      pullPolicy: Always
      repository: ghcr.io/jmbannon/ytdl-sub
      tag: "latest@sha256:b3bd00902827b4be9dcf3e2d727b35a1b86595cbebae088cc346e56e6c7bf988" # 2023-02-24 03:00 -0400

    controller:
      type: cronjob
      restartPolicy: OnFailure
      cronjob:
        # schedule: "0 0 5 31 2" # Disable cronjob by giving it a schedule that will never run # active nas
        schedule: "*/15 * * * *"
        ttlSecondsAfterFinished: 86400

    command:
      - "ytdl-sub"
      - "--log-level=debug"
      - "--config=/config/config.yaml"
      - "sub"
      - "/config/subscriptions.yaml"

    env:
      TZ: America/New_York
      PUID: 568
      PGID: 568

    persistence:
      config:
        enabled: true
        name: ytdl-sub-config
        type: configMap
        mountPath: /config
        readOnly: true
        defaultMode: 0755
      media:
        enabled: true
        existingClaim: nas-volume1-media
      tmp:
        enabled: true
        type: emptyDir
        mountPath: /tmp/ytdl-sub

    service:
      main:
        enabled: false

    ingress:
      main:
        enabled: false

    resources:
      requests:
        cpu: 100m
        memory: 128M
      limits:
        memory: 4G
