apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ytdl-sub-data-nas
  namespace: home-automation
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nas
  accessModes:
    - ReadWriteMany
