# -- This is like `sensitive-values` except these are intended to be public
# -- and therefore safe from sensitive or secret values.
apiVersion: v1
kind: ConfigMap
metadata:
  name: public-values
  namespace: flux-system
data:
  # prettier-ignore
  defaultHR_maxHistory: "2"
  defaultHR_install_remediation_retries: "3"
  defaultHR_upgrade_cleanupOnFail: "true"
  defaultHR_upgrade_remediation_retries: "3"
  defaultHR_uninstall_keepHistory: "false"
  defaultHR_patch: |-
    - op: add
          path: /spec/maxHistory
          value: 2
        - op: add
          path: /spec/install/remediation/retries
          value: 3
        - op: add
          path: /spec/upgrade/cleanupOnFail
          value: true
        - op: add
          path: /spec/upgrade/remediation/retries
          value: 3
        - op: add
          path: /spec/uninstall/keepHistory
          value: false
