# -- This is like `sensitive-values` except these are intended to be public
# -- and therefore safe from sensitive or secret values.
apiVersion: v1
kind: ConfigMap
metadata:
  name: public-values
  namespace: flux-system
data:
  # prettier-ignore
  defaultHR.maxHistory: "2"
  defaultHR.install.remediation.retries: "3"
  defaultHR.upgrade.cleanupOnFail: "true"
  defaultHR.upgrade.remediation.retries: "3"
  defaultHR.uninstall.keepHistory: "false"
