apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config
  namespace: networking
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: nas
  accessModes:
    - ReadWriteOnce
