apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex-secondary
  namespace: flux-system
spec:
  releaseName: plex-secondary
  targetNamespace: media
  chart:
    spec:
      chart: app-template
      version: "1.3.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  interval: 2m0s
  values:
    image:
      repository: plexinc/pms-docker
      tag: plexinc/pms-docker:1.31.3.6868-28fc46b27 # {"$imagepolicy": "flux-system:plex-secondary"}
    podAnnotations:
      reloader.stakater.com/auto: "true"
    controller:
      type: statefulset
      replicas: 1
    persistence:
      media:
        enabled: true
        existingClaim: nas-volume1-media
      config:
        enabled: true
        existingClaim: plex-secondary-config-longhorn-plex
      transcode:
        enabled: true
        type: hostPath
        hostPathType: DirectoryOrCreate
        hostPath: &transcode /dev/shm/transcode
        mountPath: *transcode
      dri:
        enabled: true
        type: hostPath
        hostPath: &dri /dev/dri
        mountPath: *dri
    envFrom:
      - configMapRef:
          name: plex-secondary-config
    podSecurityContext:
      supplementalGroups: [44, 109, 10000]
    service:
      main:
        enabled: true
        annotations:
          metallb.universe.tf/allow-shared-ip: media-neko
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.1.70
        ports:
          http:
            port: 32400
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-body-size: 256m
          cert-manager.io/cluster-issuer: letsencrypt
          acme.cert-manager.io/http01-edit-in-place: "false"
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: ${cloudflared_tunnel_uuid}.cfargotunnel.com
        hosts:
          - host: &host "plex-backup.${blog_domain}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: *host
            hosts:
              - *host
      nodeSelector:
        graphics: dri
        longhorn: primary
      resources:
        requests:
          cpu: 100m
        limits:
          memory: 8192Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - "plex"
