apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grav-${game_name}-data-longhorn-webapp
  namespace: personal
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: longhorn-webapp
  accessModes:
    - ReadWriteOnce
