apiVersion: v1
kind: Service
metadata:
  name: bitcoin-balance-notifier
  namespace: crypto
spec:
  type: NodePort
  selector:
    app: bitcoin-balance-notifier
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

