apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hotboxfort-neko
  namespace: flux-system
spec:
  releaseName: hotboxfort-neko
  targetNamespace: hotboxfort
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 2m0s
  valuesFrom:
    - kind: Secret
      name: hotboxfort-neko
  values:
    image:
      # repository: ghcr.io/m1k1o/neko/intel-firefox
      repository: ghcr.io/m1k1o/neko/firefox
      tag: 2.8.10

    env:
      NEKO_SCREEN: 1280x720@30
      NEKO_PROXY: "true"
      NEKO_TCPMUX: &mux "5101"
      NEKO_UDPMUX: *mux
      NEKO_ICELITE: "true"

    controller:
      type: statefulset
      replicas: 1

    persistence:
      config:
        enabled: true
        name: hotboxfort-neko-firefox-config
        type: configMap
        mountPath: /usr/lib/firefox/distribution/policies.json
        subPath: policies.json
        readOnly: true
        defaultMode: 0755
      profile:
        enabled: true
        existingClaim: hotboxfort-neko-firefox-profile-nas
        mountPath: /home/neko/.mozilla/firefox/profile.default
      dri:
        enabled: true
        type: hostPath
        hostPath: &dri /dev/dri
        mountPath: *dri
      shm:
        enabled: true
        type: hostPath
        hostPath: &shm /dev/shm
        mountPath: *shm

    # podSecurityContext:
    #   supplementalGroups: [44, 109, 10000]

    # securityContext:
    #   privileged: true

    podAnnotations:
      reloader.stakater.com/auto: "true"

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            port: 80
            targetPort: 8080
          mux:
            port: &port 5101
            targetPort: *port
          muxudp:
            port: *port
            targetPort: *port
            protocol: UDP

    resources:
      requests:
        cpu: 1000m

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          acme.cert-manager.io/http01-edit-in-place: "true"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.alpha.kubernetes.io/target: ${hotboxfort_domain_ddns}
        hosts:
          - host: movienight.${hotboxfort_domain}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: movienight.${hotboxfort_domain}-tls
            hosts:
              - movienight.${hotboxfort_domain}
