apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-longhorn-webapp
  namespace: media
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  storageClassName: longhorn-webapp
  accessModes:
    - ReadWriteOnce
