apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    logLevel: debug
    logFormat: json
    metricsNamePrefix: event_exporter_
    route:
      routes:
        - match:
          - receiver: "Discord"
          # drop:
          # - type: "Normal"
    receivers:
      - name: "Discord"
        webhook:
          endpoint: $${DISCORD_KUBE_EVENT_EXPORTER_WEBHOOK}
          headers:
            User-Agent: kube-event-exporter 1.0
          layout:
            embeds:
              - title: '{{ .Type }}: ({{ .Reason }}) {{ .Message }}'
                description: '[{{ .InvolvedObject.Kind }}] {{ .InvolvedObject.Namespace }}/{{ .InvolvedObject.Name }}'
                color: '{{ if eq .Type "Error" }}16738657{{ else }}16645526{{ end }}'
                fields:
                  - name: 'Host'
                    value: '{{ .Source.Host }}'
                    inline: false
                  - name: 'First Timestamp'
                    value: '{{ .FirstTimestamp }}'
                    inline: false
                  - name: 'Last Timestamp'
                    value: '{{ .LastTimestamp }}'
                    inline: false
