apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: go-discord-modtools-dev-db
  namespace: flux-system
spec:
  releaseName: go-discord-modtools-dev-db
  targetNamespace: personal
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 2m0s
  values:
    image:
      repository: mariadb
      tag: 10.8

    envFrom:
      - secretRef:
          name: go-discord-modtools-dev-db

    controller:
      type: statefulset
      replicas: 1 # active longhorn

    persistence:
      data:
        enabled: true
        existingClaim: go-discord-modtools-dev-mariadb-longhorn-database
        mountPath: /var/lib/mysql

    podAnnotations:
      reloader.stakater.com/auto: "true"

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            enabled: false
          sql:
            port: 3306
            nodePort: 31135

    nodeSelector:
      longhorn: primary

    resources:
      requests:
        cpu: 10m
      limits:
        memory: 512Mi
