apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: go-discord-modtools-dev
  namespace: flux-system
spec:
  releaseName: go-discord-modtools-dev
  targetNamespace: personal
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 2m0s
  values:
    controller:
      replicas: 1
    image:
      repository: ghcr.io/tyzbit/go-discord-modtools
      tag: a1c2c3e-1704821364 # {"$imagepolicy": "flux-system:go-discord-modtools-dev:tag"}
    envFrom:
      - secretRef:
          name: go-discord-modtools-dev
    probes:
      liveness:
        enabled: true
        custom: true
        spec: &spec
          httpGet:
            port: 8080
            path: /healthcheck
          failureThreshold: 3
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 5
      readiness:
        enabled: true
        custom: true
        spec: *spec
      startup:
        enabled: true
        custom: true
        spec:
          !!merge <<: *spec
          failureThreshold: 15
          initialDelaySeconds: 5
    service:
      main:
        enabled: false
        ports:
          http:
            enabled: false
    podAnnotations:
      reloader.stakater.com/auto: "true"
    resources:
      requests:
        cpu: "50m"
      limits:
        memory: "256Mi"
