apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: go-discord-modtools-dev
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: go-discord-modtools
  filterTags:
    pattern: "develop-(?P<timestamp>[0-9]+)"
    extract: "$timestamp"
  policy:
    numerical:
      order: asc
