apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-discord-modtools-dev-mariadb-longhorn-database
  namespace: personal
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn-database
  resources:
    requests:
      storage: 10Gi
