---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mediamtx
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      mediamtx:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          mediamtx:
            image:
              repository: bluenviron/mediamtx
              tag: latest-ffmpeg
            env:
              MTX_PROTOCOLS: "tcp"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

    persistence:
      config:
        name: mediamtx-config
        type: configMap
        advancedMounts:
          mediamtx:
            mediamtx:
              - path: /mediamtx.yml
                readOnly: true
                subPath: mediamtx.yml

    service:
      app:
        controller: mediamtx
        ports:
          rtsp:
            port: 554
          hls:
            port: 8888
          webrtc:
            port: 8889
          srt:
            port: 8890
          rtmp:
            port: 1935
