---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mediamtx
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      mediamtx:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          mediamtx:
            image:
              repository: bluenviron/mediamtx
              tag: latest-ffmpeg
            env:
              MTX_PROTOCOLS: "tcp"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

    persistence:
      config:
        name: mediamtx-config
        type: configMap
        advancedMounts:
          mediamtx:
            mediamtx:
              - path: /mediamtx.yml
                readOnly: true
                subPath: mediamtx.yml

    service:
      app:
        controller: mediamtx
        ports:
          rtsp:
            port: 554
          hls:
            port: 8888
          # webrtc
          http:
            port: 80
          srt:
            port: 8890
          rtmp:
            port: 1935

    ingress:
      mediamtx:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          acme.cert-manager.io/http01-edit-in-place: "true"
          # nginx.ingress.kubernetes.io/proxy-buffer-size: "128m"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
          # nginx.ingress.kubernetes.io/proxy-buffering: "off"
          # nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: ${cloudflared_tunnel_uuid}.cfargotunnel.com
        hosts:
          - host: &host "mtx.${game_domain}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
