apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-database-nas
  namespace: home-automation
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: nas
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-data-nas
  namespace: home-automation
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nas
  accessModes:
    - ReadWriteMany
