apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: revolt-${chat_name}-chat-voso
  namespace: flux-system
spec:
  releaseName: revolt-${chat_name}-chat-voso
  targetNamespace: revolt-${chat_name}-chat
  dependsOn:
    - name: revolt-${chat_name}-chat-caddy
      namespace: flux-system
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  interval: 2m0s
  values:
    image:
      # TODO: Find or make a build for the rewrite branch
      # https://github.com/revoltchat/vortex/tree/vortex
      repository: ghcr.io/revoltchat/vortex
      tag: 0.3.0-alpha.1

    envFrom:
      - secretRef:
          name: revolt-${chat_name}-chat-env

    podAnnotations:
      reloader.stakater.com/auto: "true"

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 8080

    nodeSelector:
      longhorn: primary

    resources:
      requests:
        cpu: 10m
      limits:
        memory: 128Mi
