---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: foundryvtt
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: games
  releaseName: foundryvtt
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: felddy/foundryvtt
      tag: 11.313.0

    env:
      TIMEZONE: America/New_York
      CONTAINER_CACHE: /data/container_cache
      CONTAINER_PATCHES: /data/container_patches
      CONTAINER_URL_FETCH_RETRY: "50"
      #CONTAINER_PRESERVE_CONFIG: "true"
      CONTAINER_VERBOSE: "true"
      FOUNDRY_HOSTNAME: &host "tabletop.${game_domain}"
      FOUNDRY_LOCAL_HOSTNAME: *host
      FOUNDRY_MINIFY_STATIC_FILES: "true"
      FOUNDRY_PROTOCOL: "4"
      FOUNDRY_PROXY_PORT: "443"
      FOUNDRY_PROXY_SSL: "true"
      FOUNDRY_WORLD: "menace-under-otari"
      FOUNDRY_COMPRESS_WEBSOCKET: "true"
      FOUNDRY_TELEMETRY: "false"
      #FOUNDRY_VERSION: "11.292"
      #NODE_DEBUG: "*"

    envFrom:
      - secretRef:
          name: foundryvtt

    service:
      main:
        ports:
          http:
            port: 30000

    probes:
      startup:
        enabled: false
      liveness:
        enabled: false
      readiness:
        enabled: false

      filebrowser:
        enabled: true
        primary: false
        name: foundryvtt-filebrowser
        ports:
          fbhttp:
            enabled: true
            port: 80

    additionalContainers:
      filebrowser:
        name: filebrowser
        image: filebrowser/filebrowser:v2
        args: ["-d", "/db/database.db"]
        env:
          - name: TZ
            value: America/New_York
        volumeMounts:
          - name: data
            subPath: filebrowser
            mountPath: /db
          - name: data
            mountPath: /srv/

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt
          acme.cert-manager.io/http01-edit-in-place: "true"
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: 4096m
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: ${cloudflared_tunnel_uuid}.cfargotunnel.com
        hosts:
          - host: *host
            paths:
              - path: "/"
          - host: &hostfb "tabletop-files.${game_domain}"
            paths:
              - path: "/"
                service:
                  name: foundryvtt-filebrowser
                  port: 80
        tls:
          - hosts:
              - *host
              - *hostfb
            secretName: *host

    persistence:
      data:
        enabled: true
        existingClaim: foundry-data-longhorn-gameserver

    resources:
      requests:
        cpu: 10m
      limits:
        memory: 4Gi
