---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    securityContext:
      capabilities:
        add: ["NET_BIND_SERVICE"]

    image:
      repository: jacobalberty/unifi
      tag: v7.3.83

    env:
      RUNAS_UID0: "false"
      BIND_PRIV: "false"
      UNIFI_UID: "999"
      UNIFI_GID: "999"
      UNIFI_STDOUT: "true"
      JVM_INIT_HEAP_SIZE:
      JVM_MAX_HEAP_SIZE: 1024M

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.78
        # ipFamilyPolicy: RequireDualStack
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: networking-unifi
        ports:
          http:
            enabled: true
            port: 8443
            protocol: HTTPS
      tcp:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.78
        # ipFamilyPolicy: RequireDualStack
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: networking-unifi
        ports:
          controller: &tcp
            enabled: true
            protocol: TCP
            port: 8080
          # portal-http:
          #   !!merge <<: *tcp
          #   port: 8880
          # portal-https:
          #   !!merge <<: *tcp
          #   port: 8843
          speedtest:
            !!merge <<: *tcp
            port: 6789
      udp:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.78
        # ipFamilyPolicy: RequireDualStack
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: networking-unifi
        ports:
          stun: &udp
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            !!merge <<: *udp
            enabled: true
            port: 5514
          discovery:
            !!merge <<: *udp
            port: 10001

    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 256m
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          cert-manager.io/cluster-issuer: letsencrypt
          acme.cert-manager.io/http01-edit-in-place: "false"
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: ${cloudflared_tunnel_uuid}.cfargotunnel.com
        ingressClassName: "nginx"
        hosts:
          - host: &host "unifi.${personal_domain}"
            paths:
              - path: /
        tls:
          - secretName: *host
            hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: unifi-config-longhorn-webapp
        mountPath: /unifi

    resources:
      requests:
        cpu: 50m
      limits:
        memory: 1536M
