apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overseerr
  namespace: flux-system
spec:
  targetNamespace: media
  chart:
    spec:
      chart: app-template
      version: "3.2.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 2m0s
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.33.2

    fullnameOverride: overseerr

    controller:
      replicas: 1 # active longhorn-webapp

    podSecurityContext:
      fsGroup: 568

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            port: 5055
            targetPort: 5055

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          acme.cert-manager.io/http01-edit-in-place: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: ${cloudflared_tunnel_uuid}.cfargotunnel.com
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: &public "request.${public_services_domain}"
            paths:
              - path: "/"
        tls:
          - hosts:
              - *public
            secretName: *public

    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config-longhorn-webapp
        mountPath: /app/config
    # resources:
    #   requests:
    #     cpu: 200m
    #   limits:
    #     memory: 6Gi
    # nodeSelector:
    #   kubernetes.io/hostname: cameraman
