apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sabnzbd
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m

  wait: false
  prune: true

  path: "./clusters/corpus/apps/media/sabnzbd"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn: [{ name: kubernetes-secrets }, { name: longhorn-recurring-jobs }]
  patches:
    - patch: |-
        ${defaultHR.patch}
      target:
        kind: HelmRelease
        name: sabnzbd
        # labelSelector: helmrelease-values=default
  postBuild:
    substituteFrom:
      - kind: Secret
        name: sensitive-values
