apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-longhorn-webapp
  namespace: media
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: longhorn-webapp
  accessModes:
    - ReadWriteOnce
