# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.1/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plex-secondary
  namespace: flux-system
spec:
  releaseName: *app
  targetNamespace: media
  chart:
    spec:
      chart: app-template
      version: "3.2.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 2m0s
  values:
    controllers:
      plex:
        replicas: 1 # active longhorn nas
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 44
              - 65537
          nodeSelector:
            graphics: dri
            longhorn: primary
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: "kubernetes.io/hostname"
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - "plex-secondary"

        containers:
          plex:
            image:
              repository: plexinc/pms-docker
              tag: "1.40.2.8395-c67dce28e"
            envFrom:
              - configMapRef:
                  name: plex-secondary-config
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 8192Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

    persistence:
      media:
        existingClaim: nas-volume1-media
      config:
        existingClaim: plex-secondary-config-longhorn-plex
      transcode:
        type: hostPath
        hostPathType: DirectoryOrCreate
        hostPath: /dev/shm/transcode
      dri:
        type: hostPath
        hostPath: /dev/dri

    service:
      main:
        controller: plex
        type: ClusterIP
        ports:
          http:
            port: 32400

    ingress:
      main:
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 256m
          cert-manager.io/cluster-issuer: letsencrypt
          acme.cert-manager.io/http01-edit-in-place: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.alpha.kubernetes.io/target: ${home_domain_ddns}
        hosts:
          - host: &host "backup.plex.${public_services_domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
        tls:
          - secretName: *host
            hosts:
              - *host
