apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rocketchat
  namespace: flux-system
spec:
  interval: 10m
  timeout: 1m0s
  url: https://rocketchat.github.io/helm-charts
