apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: flux-system
spec:
  releaseName: mosquitto
  targetNamespace: home-automation
  interval: 2m0s
  chart:
    spec:
      chart: app-template
      version: "1.2.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    image:
      repository: eclipse-mosquitto
      tag: 2.0.14
    env:
      TZ: America/New_York
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
            targetPort: 1883
        loadBalancerIP: 192.168.1.68
