apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: flux-system
spec:
  releaseName: mosquitto
  targetNamespace: home-automation
  interval: 2m0s
  chart:
    spec:
      chart: mosquitto
      version: "4.8.2"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    env:
      TZ: America/New_York
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.68