apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-pv-wordpress-${blog_name}
  namespace: personal
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: migrate-pv
          image: debian
          command: ["/bin/bash", "-c"]
          args:
            - apt-get update && apt-get install -y rsync &&
              ls -lah /src_vol /dst_vol &&
              df -h &&
              rsync -av --info=progress2 --delete /src_vol/ /dst_vol/ &&
              ls -lah /dst_vol/ &&
              du -shxc /src_vol/ /dst_vol/
          volumeMounts:
            - mountPath: /src_vol
              name: src
              # subPath: user
              # subPath: backup
              # subPath: logs
              # subPath: filebrowser
              readOnly: true
            - mountPath: /dst_vol
              # subPath: user
              # subPath: backup
              # subPath: logs
              # subPath: filebrowser
              name: dst
      restartPolicy: Never
      volumes:
        - name: src
          persistentVolumeClaim:
            claimName: wordpress-${blog_name}-nas
        - name: dst
          persistentVolumeClaim:
            claimName: wordpress-${blog_name}-longhorn-blog
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-pv-wordpress-hotboxfort
  namespace: hotboxfort
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: migrate-pv
          image: debian
          command: ["/bin/bash", "-c"]
          args:
            - apt-get update && apt-get install -y rsync &&
              ls -lah /src_vol /dst_vol &&
              df -h &&
              rsync -av --info=progress2 --delete /src_vol/ /dst_vol/ &&
              ls -lah /dst_vol/ &&
              du -shxc /src_vol/ /dst_vol/
          volumeMounts:
            - mountPath: /src_vol
              name: src
              # subPath: user
              # subPath: backup
              # subPath: logs
              # subPath: filebrowser
              readOnly: true
            - mountPath: /dst_vol
              # subPath: user
              # subPath: backup
              # subPath: logs
              # subPath: filebrowser
              name: dst
      restartPolicy: Never
      volumes:
        - name: src
          persistentVolumeClaim:
            claimName: wordpress-hotboxfort-nas
        - name: dst
          persistentVolumeClaim:
            claimName: wordpress-hotboxfort-longhorn-blog
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-pv-wordpress-sheanxious
  namespace: sheanxious
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: migrate-pv
          image: debian
          command: ["/bin/bash", "-c"]
          args:
            - apt-get update && apt-get install -y rsync &&
              ls -lah /src_vol /dst_vol &&
              df -h &&
              rsync -av --info=progress2 --delete /src_vol/ /dst_vol/ &&
              ls -lah /dst_vol/ &&
              du -shxc /src_vol/ /dst_vol/
          volumeMounts:
            - mountPath: /src_vol
              name: src
              # subPath: user
              # subPath: backup
              # subPath: logs
              # subPath: filebrowser
              readOnly: true
            - mountPath: /dst_vol
              # subPath: user
              # subPath: backup
              # subPath: logs
              # subPath: filebrowser
              name: dst
      restartPolicy: Never
      volumes:
        - name: src
          persistentVolumeClaim:
            claimName: wordpress-sheanxious-nas
        - name: dst
          persistentVolumeClaim:
            claimName: wordpress-sheanxious-longhorn-blog
