apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: home-automation
data:
  config.yml: |
    logger:
      default: info
      # logs:
      #   frigate.record: debug
    database:
      path: /db/frigate.db
    # model:
    #   path: plus://e97db27d57660165e7c6ddb27a747213
    mqtt:
      host: mosquitto
    record:
      enabled: True
      retain:
        days: 3
      events:
        retain:
          default: 30
          mode: active_objects
    snapshots:
      enabled: True
      retain:
        default: 30
        objects:
          person: 30
    objects:
      track:
        - person
    birdseye:
      enabled: True
      quality: 8
      width: 1920
      height: 1080
      # -- objects, motion, continuous
      mode: continuous
    ffmpeg:
      # hwaccel_args: ["-hwaccel", "vaapi", "-hwaccel_device", "/dev/dri/renderD128", "-hwaccel_output_format", "yuv420p"]
      hwaccel_args: preset-vaapi
      input_args: preset-rtsp-restream
    # go2rtc is disabled because frigate kept running out of memory and also 404ing
    # go2rtc:
    #   streams:
    #     frontdoor: 'rtsp://{FRIGATE_FRONTDOOR_CREDENTIALS}@frontdoor.onair:554'
    #     # frontdoor_low: 'rtsp://{FRIGATE_FRONTDOOR_CREDENTIALS}@frontdoor.onair:554/low'
    #     backyard: 'rtsp://{FRIGATE_BACKYARD_CREDENTIALS}@backyard.onair:554/1'
    #     driveway: 'rtsp://{FRIGATE_DRIVEWAY_CREDENTIALS}@driveway.onair:554/1'
    #     porch: 'rtsp://{FRIGATE_PORCH_CREDENTIALS}@porch.onair:554//cam/realmonitor?channel=1&subtype=0'
    #     # porch_low: 'rtsp://{FRIGATE_PORCH_CREDENTIALS}@porch.onair:554/cam/realmonitor?channel=1&subtype=1'
    #     court: 'rtsp://{FRIGATE_COURT_CREDENTIALS}@court.onair:554/cam/realmonitor?channel=1&subtype=0'
    #     # court_low: 'rtsp://{FRIGATE_COURT_CREDENTIALS}@court.onair:554/cam/realmonitor?channel=1&subtype=1'

    detectors:
      coral:
        type: edgetpu
        device: usb

    cameras:
      porch:
        birdseye:
          order: 1
        ffmpeg:
          inputs:
            # - path: 'rtsp://localhost:8554/porch'
            - path: 'rtsp://{FRIGATE_PORCH_CREDENTIALS}@porch.onair:554/live'
              roles:
                - detect
                - record
        motion:
          mask:
            - 2688,1520,1950,1520,2168,751,2688,738
        objects:
          filters:
            person:
              # min_score: 0.73
              mask:
                - 2688,1520,1950,1520,2168,751,2688,738
        detect:
          width: 1280
          height: 720
          fps: 5
        mqtt:
          height: 540

      frontdoor:
        birdseye:
          order: 2
        motion:
          mask:
            - 0,390,193,302,416,250,613,202,707,193,1021,155,1149,113,1138,0,0,0
        objects:
          filters:
            person:
              mask:
                - 0,390,193,302,416,250,613,202,707,193,1021,155,1149,113,1138,0,0,0
        ffmpeg:
          inputs:
            # - path: 'rtsp://localhost:8554/frontdoor_low'
            - path: 'rtsp://{FRIGATE_FRONTDOOR_CREDENTIALS}@frontdoor.onair:554'
              roles:
                - detect
                - record
        detect:
          width: 1280
          height: 720
          fps: 5
        mqtt:
          height: 540

      driveway:
        birdseye:
          order: 3
        ffmpeg:
          inputs:
            # - path: 'rtsp://localhost:8554/driveway'
            - path: 'rtsp://{FRIGATE_DRIVEWAY_CREDENTIALS}@driveway.onair:554/1'
              roles:
                - detect
                - record
        motion:
          mask:
           - 710,0,655,161,1280,218,1280,0
           - 90,720,0,720,0,699,207,567,257,615
        objects:
          filters:
            person:
              min_score: 0.78
              mask: 
                - 710,0,655,161,1280,218,1280,0
                - 90,720,0,720,0,699,207,567,257,615
        snapshots:
          enabled: False
        detect:
          enabled: True
          width: 1280
          height: 720
          fps: 5
        mqtt:
          height: 540

      backyard:
        birdseye:
          order: 4
        ffmpeg:
          inputs:
            # - path: 'rtsp://localhost:8554/backyard'
            - path: 'rtsp://{FRIGATE_BACKYARD_CREDENTIALS}@backyard.onair:554/1'
              roles:
                - detect
                - record
        objects:
          filters:
            person:
              min_score: 0.82
        detect:
          width: 1920
          height: 1080
          fps: 5
        mqtt:
          height: 540

      court:
        birdseye:
          order: 5
        ffmpeg:
          inputs:
            # - path: 'rtsp://localhost:8554/court'
            - path: 'rtsp://{FRIGATE_COURT_CREDENTIALS}@court.onair:554/live'
              roles:
                - record
        snapshots:
          enabled: False
        detect:
          enabled: True
          width: 1920
          height: 1080
          fps: 5
        mqtt:
          height: 540

      flowerbed:
        birdseye:
          order: 6
        ffmpeg:
          inputs:
            # - path: 'rtsp://localhost:8554/backyard'
            - path: 'rtsp://{FRIGATE_BUNNIES_CREDENTIALS}@bunnies.onair:554/1'
              roles:
                - detect
                - record
        objects:  
          track:
            - cat
            - dog
            # - horse
            # - sheep
            # - cow
            # - elephant
            # - zebra
            # - giraffe
            # - bear
          filters:
            cat: &animalthreshold
              threshold: 0.5
            dog: *animalthreshold
            # horse: *animalthreshold
            # sheep: *animalthreshold
            # cow: *animalthreshold
            # elephant: *animalthreshold
            # zebra: *animalthreshold
            # giraffe: *animalthreshold
            # bear: *animalthreshold
        detect:
          width: 1920
          height: 1080
          fps: 30
        mqtt:
          height: 540
