apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  releaseName: home-assistant
  targetNamespace: home-automation
  timeout: 15m
  interval: 2m0s
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      pullPolicy: Always
      repository: ghcr.io/home-assistant/home-assistant
      tag: "2024.1.2"

    controller:
      type: statefulset
      replicas: 1 # active longhorn-database nas

    hostNetwork: true

    dnsPolicy: ClusterFirstWithHostNet

    env:
      TZ: America/New_York

    persistence:
      dbus: # needed for Bluetooth
        enabled: true
        type: hostPath
        hostPath: &dbus /run/dbus
        mountPath: *dbus
        readOnly: true
      hci: # needed for Bluetooth
        enabled: true
        type: hostPath
        hostPath: &hci /dev/hci0
        mountPath: *hci
      config:
        enabled: true
        existingClaim: home-assistant-config-nas
      media:
        enabled: true
        type: emptyDir

    # nodeSelector:
    #   bluetooth: "true"

    additionalContainers:
      filebrowser:
        name: filebrowser
        image: filebrowser/filebrowser:v2
        args: ["-d", "/db/database.db"]
        env:
          - name: TZ
            value: America/New_York
        volumeMounts:
          - name: config
            subPath: filebrowser
            mountPath: /db
          - name: config
            mountPath: /srv/homeassistant

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          acme.cert-manager.io/http01-edit-in-place: "true"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "20"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: ${cloudflared_tunnel_uuid}.cfargotunnel.com
        hosts:
          - host: &host "home.${personal_domain}"
            paths:
              - path: "/"
          - host: &hostfb "home-fb.${personal_domain}"
            paths:
              - path: "/"
                service:
                  name: home-assistant-filebrowser
                  port: 80
        tls:
          - hosts:
              - *host
              - *hostfb
            secretName: home.${personal_domain}-multi-tls

    service:
      main: &svc
        enabled: true
        type: ClusterIP
        ports:
          http:
            port: 8123
            targetPort: 8123
          matter:
            port: 5580
            targetPort: 5580

      filebrowser:
        enabled: true
        primary: false
        name: home-assistant-filebrowser
        ports:
          fbhttp:
            enabled: true
            port: 80
