apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-secrets
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 5m

  wait: true
  prune: true

  path: "./clusters/corpus/flux-addons/core-system/secrets"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
