apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: bitcoin-balance-notifier
  namespace: flux-system
spec:
  secretRef:
    name: docker-hub
  image: docker.io/tyzbit/bitcoin-balance-notifier
  interval: 2m0s
