apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bitcoin
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: longhorn-recurring-jobs
      namespace: flux-system

  wait: false
  prune: true

  path: "./clusters/corpus/apps/crypto/bitcoin"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn: [{ name: kubernetes-secrets }, { name: longhorn-recurring-jobs }]
  postBuild:
    substituteFrom:
      - kind: Secret
        name: sensitive-values
