apiVersion: v1
kind: ConfigMap
metadata:
  name: revolt-${chat_name}-chat-caddyfile
  namespace: revolt-${chat_name}-chat
data:
  Caddyfile: |
    {$HOSTNAME} {
      route /api* {
        uri strip_prefix /api
        reverse_proxy http://revolt-${earthlings_name}-chat-api:8000
      }

      route /ws {
        @upgrade {
          header Connection *Upgrade*
          header Upgrade websocket
        }

        uri strip_prefix /ws
        reverse_proxy @upgrade http://revolt-${earthlings_name}-chat-events:9000
      }

      route /autumn* {
        uri strip_prefix /autumn
        reverse_proxy http://revolt-${earthlings_name}-chat-autumn:3000
      }

      route /january* {
        uri strip_prefix /january
        reverse_proxy http://revolt-${earthlings_name}-chat-january:7000
      }

      reverse_proxy http://revolt-${earthlings_name}-chat-web:5000
    }
