apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: writefreely-${chat_name}-chat-caddy-longhorn-webapp
  namespace: revolt-${chat_name}-chat
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn-webapp
  resources:
    requests:
      storage: 10Gi
