---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app tyz-social-semaphore
  namespace: flux-system
spec:
  releaseName: *app
  targetNamespace: personal
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      # https://github.com/ansible-semaphore/semaphore/issues/1149
      repository: semaphoreui/semaphore
      tag: v2.9.4

    env:
      TZ: America/New_York
      SEMAPHORE_BOLT_HOST: &configpath /etc/semaphore/config.json
      SEMAPHORE_DIALECT: bolt
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_LDAP_ACTIVATED: "no"

    envFrom:
      - name: &secret tyz-social-semaphore-config
        secretRef:
          name: *secret

    persistence:
      data:
        enabled: true
        existingClaim: tyz-social-semaphore-data-longhorn-webapp

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          acme.cert-manager.io/http01-edit-in-place: "false"
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: ${cloudflared_tunnel_uuid}.cfargotunnel.com
          nginx.ingress.kubernetes.io/proxy-body-size: 4096m
        hosts:
          - host: &host tyz.social
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - goto.tyz.social
              - *host
            secretName: tyz-social-gotosocial-tls

    resources:
      requests:
        cpu: 10m
      limits:
        memory: 512Mi
