apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tyz-social-semaphore-data-longhorn-webapp
  namespace: personal
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn-webapp
  resources:
    requests:
      storage: 10Gi
