apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-recurring-jobs
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 10s
  timeout: 5m
  healthChecks:
    - kind: HelmRelease
      name: longhorn

  wait: false
  prune: true

  path: "./clusters/corpus/core-system/storage/longhorn/recurring-jobs"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn: [{ name: longhorn }]
