apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grav-${tech_domain}-nas
  namespace: personal
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nas
  accessModes:
    - ReadWriteMany
