apiVersion: v1
kind: Service
metadata:
  name: grav-${tech_domain}
  namespace: personal
spec:
  type: ClusterIP
  externalTrafficPolicy: Local
  selector:
    app: grav-${tech_domain}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
