apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: nginx
  namespace: flux-system
spec:
  secretRef:
    name: universal-image-pull-secret
  image: docker.io/nginx
  interval: 5m0s
